In [1]:
import numpy as np

In [2]:
import array

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
np.array([1,2,3,4,5, "deep", 4+8j])

array(['1', '2', '3', '4', '5', 'deep', '(4+8j)'], dtype='<U11')

In [6]:
np.array([1,2,3,4.5,6.0])

array([1. , 2. , 3. , 4.5, 6. ])

In [8]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [9]:
np.array([[1,3],[3,4],[6,7,8]])

<ipython-input-9-2fc331c0f648>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[1,3],[3,4],[6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [11]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [12]:
np.array([1,2,3], ndmin = 3)

array([[[1, 2, 3]]])

In [13]:
np.array([1,2,3], ndmin = 30)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [14]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [16]:
np.array([1,2,3], dtype = int)

array([1, 2, 3])

In [15]:
np.array([(1,2),(4,5)])

array([[1, 2],
       [4, 5]])

In [18]:
arr = np.array([(1,2),(4,5)], dtype = [("a", '<i2'), ("b",'<i8')])

In [19]:
arr[0][0]

1

In [20]:
type(arr[0][0])

numpy.int16

In [21]:
type(arr[0][1])

numpy.int64

In [22]:
arr = np.array([[1,3],[3,4]])

In [23]:
arr

array([[1, 3],
       [3, 4]])

In [25]:
arr[0][1]

3

In [27]:
arr[1][0]

3

In [28]:
np.mat(arr)

matrix([[1, 3],
        [3, 4]])

In [29]:
np.matrix(arr)

matrix([[1, 3],
        [3, 4]])

In [30]:
l = [3,4,5,6,7]

In [31]:
np.array(l)

array([3, 4, 5, 6, 7])

In [32]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [33]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [34]:
mat = np.matrix(arr)

In [36]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 4]])

In [37]:
np.asarray(mat)

array([[1, 3],
       [3, 4]])

In [38]:
issubclass(np.matrix, np.ndarray)

True

In [39]:
issubclass( np.ndarray, np.matrix)

False

In [40]:
arr

array([[1, 3],
       [3, 4]])

In [41]:
a = arr

In [42]:
b = np.copy(arr)

In [43]:
arr[0][0] = 67

In [44]:
arr

array([[67,  3],
       [ 3,  4]])

In [45]:
a

array([[67,  3],
       [ 3,  4]])

In [46]:
b

array([[1, 3],
       [3, 4]])

In [47]:
arr[-1]

array([3, 4])

In [48]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [49]:
for i in arr:
    for j in i:
        print(j)

67
3
3
4


In [50]:
np.fromfunction(lambda i , j : i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [51]:
type(np.fromfunction(lambda i , j : i==j,(4,4)))

numpy.ndarray

In [52]:
np.fromfunction(lambda i , j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [54]:
np.fromfunction(lambda i , j : i/j,(3,3))

<ipython-input-54-231d4427c425>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i , j : i/j,(3,3))
<ipython-input-54-231d4427c425>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i , j : i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [55]:
(i*i for i in range(5))

<generator object <genexpr> at 0x00000122E17D02E0>

In [56]:
def test(x):
        yield x

In [57]:
test(5)

<generator object test at 0x00000122E17D0970>

In [58]:
gen = (i*i for i in range(5))

In [59]:
gen

<generator object <genexpr> at 0x00000122E17D0B30>

In [63]:
for i in gen:
    print(i)

In [61]:
np.fromiter(gen, dtype = int)

array([ 0,  1,  4,  9, 16])

In [62]:
np.fromiter(range(5), dtype = int)

array([0, 1, 2, 3, 4])

In [65]:
np.fromstring('1,2,3,4,5', sep = ',', dtype = int)

array([1, 2, 3, 4, 5])

In [69]:
np.fromstring("4545 5454 214 245", sep = ' ', dtype = complex)

array([4545.+0.j, 5454.+0.j,  214.+0.j,  245.+0.j])

In [70]:
l = [3,4,5,6,7,8]

In [86]:
arr = np.array(l)

In [78]:
arr1 = np.array([[1,2,3,4], [2,3,4,5], [4,5,6,7]])

In [79]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [80]:
type(arr)

numpy.ndarray

In [81]:
arr1.ndim

2

In [82]:
arr1.size

12

In [83]:
arr1.shape

(3, 4)

In [84]:
arr1.dtype

dtype('int32')

In [87]:
arr

array([3, 4, 5, 6, 7, 8])

In [88]:
arr.size

6

In [89]:
arr.ndim

1

In [90]:
arr.shape

(6,)

In [93]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]], [[1,2,3,4],[4,5,6,7]]])

In [94]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [95]:
arr2.size

16

In [96]:
arr2.ndim

3

In [97]:
arr2.shape

(2, 2, 4)

In [98]:
range(5)

range(0, 5)

In [99]:
list(range(5))

[0, 1, 2, 3, 4]

In [100]:
list(range(6.6))

TypeError: 'float' object cannot be interpreted as an integer

In [103]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [104]:
np.arange(6.6, dtype = int)

array([0, 1, 2, 3, 4, 5, 6])

In [105]:
np.arange(6.6, 9 , 0.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [107]:
np.arange(6.6, 9, -0.3)

array([], dtype=float64)

In [108]:
np.arange(9, 6.6, -0.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [109]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [110]:
np.linspace(3,8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [113]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [111]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [112]:
np.linspace(.3,.5,5)

array([0.3 , 0.35, 0.4 , 0.45, 0.5 ])

In [114]:
np.linspace(2,8,5)

array([2. , 3.5, 5. , 6.5, 8. ])

In [115]:
np.linspace(2,8)

array([2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
       2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
       3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
       3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
       4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551,
       5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
       5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
       6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
       6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
       7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ])

In [116]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [117]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [118]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [120]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [122]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [123]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [124]:
np.zeros((2,5,4,1))

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [125]:
np.ones(4)

array([1., 1., 1., 1.])

In [126]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [127]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [128]:
np.ones((2,3,1)) +5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [129]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [130]:
np.empty((3,4))

array([[0.        , 0.        , 0.        , 1.        ],
       [0.5       , 0.33333333, 2.        , 1.        ],
       [0.66666667, 3.        , 1.5       , 1.        ]])

In [131]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [134]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [135]:
np.linspace(2,4,4, endpoint=False)

array([2. , 2.5, 3. , 3.5])

In [136]:
np.linspace(2,4,4, endpoint=False, axis = 0)

array([2. , 2.5, 3. , 3.5])

In [137]:
np.linspace(2,4,4, endpoint=False, axis = 1)

AxisError: destination: axis 1 is out of bounds for array of dimension 1

In [139]:
np.linspace([1,2],4, endpoint=False, axis = 1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96]])

In [140]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [142]:
np.logspace([2,3],4, axis = 1)

array([[  100.        ,   109.8541142 ,   120.67926406,   132.57113656,
          145.63484775,   159.98587196,   175.75106249,   193.06977289,
          212.09508879,   232.99518105,   255.95479227,   281.1768698 ,
          308.88435965,   339.32217719,   372.75937203,   409.49150624,
          449.8432669 ,   494.17133613,   542.86754393,   596.36233166,
          655.12855686,   719.685673  ,   790.60432109,   868.51137375,
          954.09547635,  1048.11313415,  1151.39539933,  1264.85521686,
         1389.49549437,  1526.41796718,  1676.83293681,  1842.06996933,
         2023.58964773,  2222.99648253,  2442.05309455,  2682.69579528,
         2947.05170255,  3237.45754282,  3556.48030622,  3906.93993705,
         4291.93426013,  4714.86636346,  5179.47467923,  5689.86602902,
         6250.55192527,  6866.48845004,  7543.12006335,  8286.42772855,
         9102.98177992, 10000.        ],
       [ 1000.        ,  1048.11313415,  1098.54114199,  1151.39539933,
         1206.79264064,

In [145]:
np.logspace([2,5],[3], axis = 0)

array([[   100.        , 100000.        ],
       [   104.81131342,  91029.81779915],
       [   109.8541142 ,  82864.27728547],
       [   115.13953993,  75431.20063355],
       [   120.67926406,  68664.88450043],
       [   126.48552169,  62505.51925274],
       [   132.57113656,  56898.66029018],
       [   138.94954944,  51794.74679231],
       [   145.63484775,  47148.66363457],
       [   152.64179672,  42919.34260129],
       [   159.98587196,  39069.39937055],
       [   167.68329368,  35564.80306223],
       [   175.75106249,  32374.57542818],
       [   184.20699693,  29470.51702552],
       [   193.06977289,  26826.9579528 ],
       [   202.35896477,  24420.53094549],
       [   212.09508879,  22229.96482526],
       [   222.29964825,  20235.89647725],
       [   232.99518105,  18420.69969327],
       [   244.20530945,  16768.32936811],
       [   255.95479227,  15264.17967175],
       [   268.26957953,  13894.95494373],
       [   281.1768698 ,  12648.55216855],
       [   

In [146]:
d = np.linspace(4,7,40)

In [147]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [148]:
d.ndim

1

In [149]:
d.shape

(40,)

In [150]:
d.size

40

In [152]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [154]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [155]:
d.reshape(1,2,1,20)

array([[[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
          4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
          4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
          5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

        [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
          5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
          6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
          6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]]])

In [156]:
np.random.rand(3)

array([0.00858378, 0.52771552, 0.65051639])

In [157]:
np.random.randn(5)

array([-0.4045924 ,  0.49048513, -0.34572114, -0.30992521,  1.53840548])

In [159]:
np.random.randn(2,3)

array([[-0.12556521,  1.5145288 , -0.50463117],
       [ 0.15463065, -1.08089512,  0.99895357]])

In [160]:
np.random.randn(2,2,3)

array([[[-0.67849769,  1.62585993,  1.01126821],
        [-0.9660626 , -0.20310709, -1.18117524]],

       [[ 1.41786209, -0.55954521,  0.88424359],
        [ 0.35717384, -0.25150047,  1.02047394]]])

In [166]:
np.random.randint(5)

4

In [178]:
np.random.randint(5,60)

16

In [179]:
np.random.randint(5,60, (4,4))

array([[16, 37, 17, 42],
       [10, 46, 28, 58],
       [37, 53, 12, 41],
       [16, 43, 37, 23]])

In [181]:
arr = np.random.randint(3,9, (3,3))

In [182]:
arr

array([[4, 5, 4],
       [8, 3, 4],
       [4, 6, 8]])

In [183]:
arr.reshape(1,9)

array([[4, 5, 4, 8, 3, 4, 4, 6, 8]])

In [184]:
arr.reshape(9,1)

array([[4],
       [5],
       [4],
       [8],
       [3],
       [4],
       [4],
       [6],
       [8]])

In [185]:
arr.reshape(1,1,9)

array([[[4, 5, 4, 8, 3, 4, 4, 6, 8]]])

In [186]:
arr.reshape(3,3,1)

array([[[4],
        [5],
        [4]],

       [[8],
        [3],
        [4]],

       [[4],
        [6],
        [8]]])

In [187]:
arr.reshape(3,-1)

array([[4, 5, 4],
       [8, 3, 4],
       [4, 6, 8]])

In [188]:
arr.reshape(1,-134531)

array([[4, 5, 4, 8, 3, 4, 4, 6, 8]])

In [189]:
arr

array([[4, 5, 4],
       [8, 3, 4],
       [4, 6, 8]])

In [191]:
arr.max()

8

In [192]:
arr.min()

3

In [194]:
arr = np.random.randint(4,100,(5,5))

In [195]:
arr

array([[ 5, 86, 95, 54, 79],
       [27, 92, 61, 18, 83],
       [51, 38, 63, 73, 55],
       [95, 73, 50, 68, 38],
       [50, 51, 15, 58, 17]])

In [196]:
arr[3:, 3:]

array([[68, 38],
       [58, 17]])

In [198]:
arr[:,[1,3]]

array([[86, 54],
       [92, 18],
       [38, 73],
       [73, 68],
       [51, 58]])

In [199]:
arr

array([[ 5, 86, 95, 54, 79],
       [27, 92, 61, 18, 83],
       [51, 38, 63, 73, 55],
       [95, 73, 50, 68, 38],
       [50, 51, 15, 58, 17]])

In [200]:
arr>10

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [201]:
arr[arr>10]

array([86, 95, 54, 79, 27, 92, 61, 18, 83, 51, 38, 63, 73, 55, 95, 73, 50,
       68, 38, 50, 51, 15, 58, 17])

In [202]:
arr

array([[ 5, 86, 95, 54, 79],
       [27, 92, 61, 18, 83],
       [51, 38, 63, 73, 55],
       [95, 73, 50, 68, 38],
       [50, 51, 15, 58, 17]])

In [203]:
arr * arr

array([[  25, 7396, 9025, 2916, 6241],
       [ 729, 8464, 3721,  324, 6889],
       [2601, 1444, 3969, 5329, 3025],
       [9025, 5329, 2500, 4624, 1444],
       [2500, 2601,  225, 3364,  289]])

In [205]:
arr1 = np.random.randint(2,4,(3,3))

In [206]:
arr2 = np.random.randint(2,3,(3,3))

In [207]:
arr1

array([[2, 2, 3],
       [2, 2, 3],
       [3, 3, 2]])

In [208]:
arr2

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [210]:
arr1*arr2

array([[4, 4, 6],
       [4, 4, 6],
       [6, 6, 4]])

In [ ]:
# if arr has diiferent shape then multiplication can't be done.

In [211]:
arr1@arr2

array([[14, 14, 14],
       [14, 14, 14],
       [16, 16, 16]])

In [212]:
arr  = np.zeros((3,4))

In [213]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [215]:
a = np.array([1,2,3,4])

In [216]:
a

array([1, 2, 3, 4])

In [217]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [218]:
arr +5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [219]:
b = np.array([5,6,7])

In [220]:
b

array([5, 6, 7])

In [221]:
b.reshape(3,1) +arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [222]:
b

array([5, 6, 7])

In [224]:
b.T

array([5, 6, 7])

In [225]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [226]:
b = arr +a

In [227]:
b

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [228]:
b.T

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [229]:
arr = np.random.rand(5,4)

In [230]:
arr

array([[0.53504551, 0.46511911, 0.8581652 , 0.77175084],
       [0.8807849 , 0.82875017, 0.83001015, 0.33028185],
       [0.91750982, 0.31905071, 0.32983375, 0.85138392],
       [0.85256804, 0.52954329, 0.48966738, 0.23607462],
       [0.98418918, 0.85735106, 0.6348503 , 0.10263108]])

In [231]:
np.sqrt(arr)

array([[0.73146805, 0.68199641, 0.92637206, 0.87849351],
       [0.93850141, 0.91035716, 0.91104893, 0.57470153],
       [0.95786733, 0.56484574, 0.57431154, 0.92270467],
       [0.92334611, 0.72769725, 0.69976238, 0.48587511],
       [0.99206309, 0.92593253, 0.79677494, 0.32036086]])

In [232]:
np.exp(arr)

array([[1.70752596, 1.59220382, 2.35882875, 2.16355098],
       [2.41279277, 2.29045426, 2.29334202, 1.39136023],
       [2.50304959, 1.37582109, 1.39073689, 2.34288697],
       [2.34566289, 1.69815656, 1.63177337, 1.26626879],
       [2.67564155, 2.3569091 , 1.88673967, 1.10808254]])

In [233]:
np.log10(arr)

array([[-0.27160927, -0.33243582, -0.0664291 , -0.11252289],
       [-0.05513014, -0.08157637, -0.0809166 , -0.48111529],
       [-0.03738928, -0.49614028, -0.48170491, -0.06987456],
       [-0.06927095, -0.27609853, -0.31009882, -0.6269507 ],
       [-0.00692141, -0.06684131, -0.19732867, -0.98872111]])

In [234]:
arr1 = np.random.randint(2,5,(5,5))

In [235]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.30103   , 0.60205999, 0.60205999],
       [0.47712125, 0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.47712125, 0.30103   , 0.60205999, 0.60205999],
       [0.30103   , 0.47712125, 0.47712125, 0.30103   , 0.60205999],
       [0.30103   , 0.47712125, 0.47712125, 0.30103   , 0.30103   ]])

In [236]:
arr1

array([[3, 3, 2, 4, 4],
       [3, 3, 3, 3, 3],
       [4, 3, 2, 4, 4],
       [2, 3, 3, 2, 4],
       [2, 3, 3, 2, 2]])

In [245]:
np.random.seed(30)
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])