In [4]:
import numpy as np
A = np.array([
        [3,7],
        [-4,-6],
        [7,8],
        [1,-1],
        [-4,-1],
        [-3,-7]
        ])

In [5]:
A

array([[ 3,  7],
       [-4, -6],
       [ 7,  8],
       [ 1, -1],
       [-4, -1],
       [-3, -7]])

In [6]:
A.shape

(6, 2)

In [7]:
import pandas as pd

In [10]:
df = pd.DataFrame(A, columns=['a0','a1'])

In [11]:
df

a0  a1
0   3   7
1  -4  -6
2   7   8
3   1  -1
4  -4  -1
5  -3  -7

In [12]:
a0 = A[:,0]
a1 = A[:,1]

In [13]:
a0

array([ 3, -4,  7,  1, -4, -3])

In [14]:
a1

array([ 7, -6,  8, -1, -1, -7])

In [15]:
np.cov(a0,a1)

array([[20., 25.],
       [25., 40.]])

In [16]:
# to find the Co-Variance
np.sum(a0*a1)/5

25.0

In [17]:
#another way to find the Co-variance

In [18]:
A

array([[ 3,  7],
       [-4, -6],
       [ 7,  8],
       [ 1, -1],
       [-4, -1],
       [-3, -7]])

In [19]:
A.T

array([[ 3, -4,  7,  1, -4, -3],
       [ 7, -6,  8, -1, -1, -7]])

In [21]:
sigma = A.T @ A/5

In [23]:
l,x = np.linalg.eig(sigma)

In [24]:
l

array([ 3.07417596, 56.92582404])

In [25]:
x

array([[-0.82806723, -0.56062881],
       [ 0.56062881, -0.82806723]])

In [26]:
sigma

array([[20., 25.],
       [25., 40.]])

In [27]:
sigma@x[:,0]

array([-2.54562438,  1.72347161])

In [28]:
sigma@x[:,1]

array([-31.91425695, -47.13840945])

In [29]:
print("first principal component")
x[:,1]

first principal component


array([-0.56062881, -0.82806723])

In [30]:
print("second principle component")
x[:,0]

second principle component


array([-0.82806723,  0.56062881])